version: "3"

networks:
  playground_default:
    external: true

services:
  trexor:
    build: ./docker-webserver
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.trexor.rule=Host(`trexor.kestrl.co.uk`)
      - traefik.http.routers.trexor.tls=true
      - traefik.http.routers.trexor.tls.certresolver=le
    environment:
      - LARAVEL_APP=1
      - COMPOSER_INSTALL_ON_BUILD=1
      - RUN_LARAVEL_MIGRATIONS_ON_BUILD=1
    networks:
      - playground_default
    volumes:
      - .:/var/www